### ISSUE TITLE
spark 接入langchain

### ISSUE THREAD

**Issue by shell-nlp** [iflytek/spark-ai-python#1]
到目前为止， 文心一言，通义千问，百川等闭源模型，都在langchain提供了官方的 langchain 实现，方便用户使用 langchain生态直接进行开发， 而星火模型目前为止，仍然没有 和 langchain 进行集成，导致在开发过程中非常麻烦。 希望可以 在langchain官方进行 星火大模型的集成。

**Comment by whybeyoung** [comment]
社区已经支持
