### ISSUE TITLE
Support Spark Embedding

### ISSUE THREAD

**Issue by whybeyoung** [iflytek/spark-ai-python#10]
we will support spark embedding according the doc:

[documentation](https://www.xfyun.cn/doc/spark/Embedding_api.html)

**Comment by bwl0211** [comment]
I will work on this issue.

**Comment by whybeyoung** [comment]
> I will work on this issue.

grats~

**Comment by whybeyoung** [comment]
https://github.com/iflytek/spark-ai-python?tab=readme-ov-file#llamaindex-support
