### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by eyuansu62** [iflytek/spark-ai-python#16]
class Spark:

    def __init__(self, model_name: str = "spark_3.5"):
        self.model_name = model_name
        self.client = ChatSparkLLM(
            spark_api_url=SPARKAI_URL,
            spark_app_id=SPARKAI_APP_ID,
            spark_api_key=SPARKAI_API_KEY,
            spark_api_secret=SPARKAI_API_SECRET,
            spark_llm_domain=SPARKAI_DOMAIN,
            streaming=False,
            request_timeout=300
    )

    def chat(self, messages, max_tokens=2048, **kwargs):
        content = messages
        try:
            messages = [ChatMessage(
                role="system",
                content='You are a helpful assistant.'
            ),
                ChatMessage(
                role="user",
                content=content
            )]
            handler = ChunkPrintHandler()
            a = self.client.generate([messages], callbacks=[handler])
            # pdb.set_trace()
            time.sleep(2)
            return a.generations[0][0].text, 0
        except ConnectionError as e:
            return "content filter", 0
        except IndexError:
            return "content filter", 0

def get_answer(client, question):

    print(client.chat(question)[0], "********")

if __name__ == '__main__':
    import concurrent.futures
    import tqdm

    questions = ["***", "***"]
    client = Spark()
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
            futures = []
            for question in questions:
                future = executor.submit(
                    get_answer,
                    client,
                    question
                )
                futures.append(future)

            for future in tqdm.tqdm(
                concurrent.futures.as_completed(futures), total=len(futures)
            ):
                future.result()
当请求速度过快时，返回的答案会揉在一起。

**Comment by whybeyoung** [comment]
当前 Client 不支持多路复用， Client为单路的client，多线程需要实例化多个client
