### ISSUE TITLE
该讯飞大模型接口支持python的asyncio异步接口吗？

### ISSUE THREAD

**Issue by tiebingice** [iflytek/spark-ai-python#20]
我们打算使用你们的讯飞大模型进行项目开发，需要使用异步调用方式，项目依赖中好像有aiohttp，请问该讯飞大模型是否支持python的asyncio异步方式调用。

**Comment by whybeyoung** [comment]
指的是这里吗？ https://github.com/iflytek/spark-ai-python?tab=readme-ov-file#%E6%96%B9%E5%BC%8F2-streamastream%E6%8E%A5%E5%8F%A3
