### ISSUE TITLE
在generate中当最后一个chunk stop的时候，加上usage信息，统计使用token方便计费

### ISSUE THREAD

**Issue by charlesluo2014** [iflytek/spark-ai-python#21]
在其它的模型接口Stream方式最后一个chunk都是有usage信息的，这样方便在结束对话后进行计费处理，而目前是在Callback on_llm_new_token 才能获取到，处理起来比较麻烦，直接在最后一个chunk处理就可以了

**Comment by whybeyoung** [comment]
@charlesluo2014 generate的返回值里 有  usage信息
