### ISSUE TITLE
a = spark.generate([messages], callbacks=[handler])输出

### ISSUE THREAD

**Issue by yyftzlq** [iflytek/spark-ai-python#35]
print(a)
结果为：generations=[[ChatGeneration(text='你好！有什么我可以帮助你的吗？', message=AIMessage(content='你好！有什么我可以帮助你的吗？'))]] llm_output={'token_usage': {'question_tokens': 11,ion_tokens': 9, 'total_tokens': 20}} run=[RunInfo(run_id=UUID('216e57c3-2ef5-4f73-a2c9-2e6b4226103b'))]
python怎么取出回答的文本呢？

**Comment by bwl0211** [comment]
通过a.generations[0][0].text 取出回答的文本~
![image](https://github.com/iflytek/spark-ai-python/assets/104616643/76415adb-1a0d-4e70-808b-391dcc3dfd8c)

**Comment by bwl0211** [comment]
通过a.generations[0][0].text 取出回答文本~
![image](https://github.com/iflytek/spark-ai-python/assets/104616643/fbba6dc4-d1a3-4acc-ac2c-e04b4f0ceaad)
