### ISSUE TITLE
关于使用多线程发送generate（）时， API模型返回内容为空，或者出现No completion Generate 和 Error Code: 11202, Error: AppIdQpsOverFlowError

### ISSUE THREAD

**Issue by hoodiexxx** [iflytek/spark-ai-python#39]
![image](https://github.com/iflytek/spark-ai-python/assets/113127111/92ea0547-8fe6-4533-adc5-3f1923278724)
![image](https://github.com/iflytek/spark-ai-python/assets/113127111/e0f1cf98-ddfe-421c-b6d0-8d47b28a6319)
![image](https://github.com/iflytek/spark-ai-python/assets/113127111/55305527-7531-4cc0-a503-309d0340848a)
future.result() 拿到的结果总是有问题， 单线程时没有这种情况

**Comment by bwl0211** [comment]
API调用会对QPS进行限制，具体请到https://www.xfyun.cn/控制台查看对应ID的QPS。
