### ISSUE TITLE
生态支持：LLamaIndex Support模块报错

### ISSUE THREAD

**Issue by feifei-1997** [iflytek/spark-ai-python#41]
ValueError: Error from embedding service:10404:no category route found
似乎是由于在获取embedding时发生了错误。错误代码为10404，表示没有找到类别路由，有没有知道是什么原因的啊。

**Comment by bwl0211** [comment]
需配置embedding model和LLM model两部分，SPARKAI_Embedding_DOMAIN为query或para。具体详见https://www.xfyun.cn/doc/spark/Embedding_api.html#_3-%E8%AF%B7%E6%B1%82
