### ISSUE TITLE
怎么控制是否请求网络哇，search_disable 开关无效

### ISSUE THREAD

**Issue by lluck42** [iflytek/spark-ai-python#43]
spark = ChatSparkLLM(
    spark_api_url=SWITCH_SPARKAI_URL(self.llm_version),
    spark_app_id=SPARKAI_APP_ID,
    spark_api_key=SPARKAI_API_KEY,
    spark_api_secret=SPARKAI_API_SECRET,
    spark_llm_domain = self.llm_version, # SPARKAI_DOMAIN 平台上这里指的是 version
    request_timeout=30,
    streaming=True,
    model_kwargs={"search_disable": not self.web_search},
)

print(not self.web_search)
问今天是几号，开关打开还是关闭结果都一样。都可以回答出来

**Comment by whybeyoung** [comment]
这个参数只在讯飞内部开放
