### ISSUE TITLE
希望把llama index的依赖变成可选安装

### ISSUE THREAD

**Issue by SomeoneKong** [iflytek/spark-ai-python#47]
目前llama index项目已经分拆出一大堆子项目，而这些内容对于不使用它的用户来说都是不必要的。
希望能够增加其他安装选项，可选地避免引入llama index依赖。
建议是默认不要引入该依赖，用户有需要时单独安装该依赖。

**Comment by whybeyoung** [comment]
ok，近期会安排更新

**Comment by whybeyoung** [comment]
按照文档更新， 默认不会安装 lama_index依赖
