### ISSUE TITLE
模拟openai的接口调用失败

### ISSUE THREAD

**Issue by dxjjhm** [iflytek/spark-ai-python#6]
from openai import OpenAI

client = OpenAI(api_key="x&x&x", base_url="http://0.0.0.0:8008")
# 正式做了相关替换

stream = client.chat.completions.create(
    model="gpt-4",
    messages=[{"role": "user", "content": "Say this is a test"}],
    stream=True,
)
for chunk in stream:
    print(chunk.choices[0].delta.content or "", end="")

运行报错
openai.InternalServerError: Error code: 502

**Comment by whybeyoung** [comment]
model="gpt-4" 换成讯飞的  domain试试。 另这个特性暂时用于实验性质

**Comment by dm57** [comment]
你需要将proxy部署起来，然后base换成你部署的监听地址，domain选择generalv3.5

**Comment by whybeyoung** [comment]
没有更多信息， 自动关闭
