### ISSUE TITLE
websocket接口如何获取app_id、api_key、api_secret

### ISSUE THREAD

**Issue by aidejieceng** [iflytek/spark-ai-python#7]
你好，作为公司的内部团队，星火引擎在业务部门内网会进行离线部署。星火推理引擎部署成功后，会有一个websocket的api接口，例如：ws://ip:9991/turing/v3/chat。

但README中，介绍了如何在开放平台申请app_id、api_key、api_secret，离线部署的引擎如何获取这三个值？

**Comment by whybeyoung** [comment]
这里主要是对公的产品的sdk，内部的话，ixf联系我 ybyang7@iflytek.com
