### ISSUE TITLE
支持星火大模型图片理解API

### ISSUE THREAD

**Issue by zhou-zl18** [iflytek/spark-ai-python#9]
很好用的库，感谢开发者。
请问能否支持图片输入呢？

**Comment by whybeyoung** [comment]
是期望调用图片的大模型服务吗

**Comment by zhou-zl18** [comment]
> 是期望调用图片的大模型服务吗

是的，希望能调用星火大模型的[图片理解](https://www.xfyun.cn/doc/spark/ImageUnderstanding.html)

**Comment by whybeyoung** [comment]
> > 是期望调用图片的大模型服务吗
> 
> 是的，希望能调用星火大模型的[图片理解](https://www.xfyun.cn/doc/spark/ImageUnderstanding.html)

ok , 我们排期

**Comment by whybeyoung** [comment]
@zhou-zl18 已支持 0.3.36版本，稍后可以使用pip install --upgrade更新
